# Form implementation generated from reading ui file 'client/design/design.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(760, 583)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 741, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.chat = QtWidgets.QWidget()
        self.chat.setObjectName("chat")
        self.chatbox = QtWidgets.QTextBrowser(parent=self.chat)
        self.chatbox.setGeometry(QtCore.QRect(10, 10, 721, 371))
        self.chatbox.setObjectName("chatbox")
        self.user_message = QtWidgets.QLineEdit(parent=self.chat)
        self.user_message.setGeometry(QtCore.QRect(10, 390, 721, 61))
        self.user_message.setObjectName("user_message")
        self.send_message = QtWidgets.QPushButton(parent=self.chat)
        self.send_message.setGeometry(QtCore.QRect(10, 460, 351, 71))
        self.send_message.setObjectName("send_message")
        self.exit = QtWidgets.QPushButton(parent=self.chat)
        self.exit.setGeometry(QtCore.QRect(370, 460, 361, 71))
        self.exit.setObjectName("exit")
        self.tabWidget.addTab(self.chat, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.nikname = QtWidgets.QLineEdit(parent=self.settings)
        self.nikname.setGeometry(QtCore.QRect(10, 10, 721, 61))
        self.nikname.setObjectName("nikname")
        self.server_port = QtWidgets.QLineEdit(parent=self.settings)
        self.server_port.setGeometry(QtCore.QRect(10, 150, 721, 61))
        self.server_port.setObjectName("server_port")
        self.server_ip = QtWidgets.QLineEdit(parent=self.settings)
        self.server_ip.setGeometry(QtCore.QRect(10, 80, 721, 61))
        self.server_ip.setObjectName("server_ip")
        self.connect = QtWidgets.QPushButton(parent=self.settings)
        self.connect.setGeometry(QtCore.QRect(10, 220, 357, 71))
        self.connect.setObjectName("connect")
        self.save_settings = QtWidgets.QPushButton(parent=self.settings)
        self.save_settings.setGeometry(QtCore.QRect(374, 220, 357, 71))
        self.save_settings.setObjectName("save_settings")
        self.go_to_chat = QtWidgets.QPushButton(parent=self.settings)
        self.go_to_chat.setGeometry(QtCore.QRect(10, 290, 721, 71))
        self.go_to_chat.setObjectName("go_to_chat")
        self.tabWidget.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat"))
        self.user_message.setPlaceholderText(_translate("MainWindow", "Enter message"))
        self.send_message.setText(_translate("MainWindow", "Send message"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat), _translate("MainWindow", "Chat"))
        self.nikname.setPlaceholderText(_translate("MainWindow", "Nikname"))
        self.server_port.setPlaceholderText(_translate("MainWindow", "Server port"))
        self.server_ip.setPlaceholderText(_translate("MainWindow", "Server IP"))
        self.connect.setText(_translate("MainWindow", "Connect"))
        self.save_settings.setText(_translate("MainWindow", "Save settings"))
        self.go_to_chat.setText(_translate("MainWindow", "Go to chat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
